use std::time::SystemTime;
use chrono::{DateTime, Utc};
use std::env;
use std::fs::{self, File};
use std::path::Path;
use tar::Builder;
use zstd::stream::write::Encoder;
use std::io::Write;

fn main() {
  println!("cargo:rerun-if-changed=Cargo.toml");
  println!("cargo:rerun-if-changed=resources");
  println!("cargo:rerun-if-changed=resources/gromrik");
  println!("cargo:rerun-if-changed=resources/lyranis");
  let build_name = env!("CARGO_PKG_NAME");
  println!("cargo:rustc-env=BUILD_NAME={}",build_name);
  let build_time: DateTime<Utc> = SystemTime::now().into();
  println!("cargo:rustc-env=BUILD_TIME={}",build_time.to_rfc3339());
  let build_id: i64 = build_time.timestamp_millis();
  println!("cargo:rustc-env=BUILD_ID={}",build_id);
  let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
  let codegen_path = Path::new(&manifest_dir).join("src").join("persona_bundles.rs");
  let mut codegen_file = File::create(&codegen_path).unwrap();
  writeln!(codegen_file,"// =========================================================================").unwrap();
  writeln!(codegen_file,"// AUTOMATICALLY GENERATED FILE - DO NOT EDIT MANUALLY").unwrap();
  writeln!(codegen_file,"// =========================================================================").unwrap();
  writeln!(codegen_file,"// This file is generated by the build.rs script during compilation.").unwrap();
  writeln!(codegen_file,"// It scans the 'resources/' directory and embeds all valid '.grom' bundles").unwrap();
  writeln!(codegen_file,"// straight into the application binary as static byte slices.").unwrap();
  writeln!(codegen_file,"// =========================================================================\n").unwrap();
  let resources_dir = Path::new(&manifest_dir).join("resources");
  let entries = fs::read_dir(&resources_dir).expect("Critical Error: 'resources' directory missing");
  let bundle_dir = Path::new(&manifest_dir).join("persona_bundles");
  if !bundle_dir.exists() {
    fs::create_dir_all(&bundle_dir).expect("Failed to create persona_bundles folder");
  }
  let mut personas: Vec<String> = Vec::new();
  for entry in entries {
    let entry = entry.unwrap();
    let path = entry.path();
    if path.is_dir() {
      let bundle_dir = path.join("bundle");
      if bundle_dir.exists() && bundle_dir.is_dir() {
        let persona_name = path.file_name().unwrap().to_str().unwrap().to_string();
        let output_path = path.join(format!("{}.grom", persona_name));
        let output_file = File::create(&output_path).unwrap();
        let compressor = Encoder::new(output_file, 15).unwrap().auto_finish();
        let mut tar_builder = Builder::new(compressor);
        let bundle_files = fs::read_dir(&bundle_dir).unwrap();
        for file_entry in bundle_files {
          let file_entry = file_entry.unwrap();
          let file_path = file_entry.path();
          if file_path.is_file() {
            let filename = file_path.file_name().unwrap().to_str().unwrap();
            tar_builder.append_path_with_name(&file_path, filename).unwrap();
          }
        }
        tar_builder.finish().unwrap();
        let _encoder_ = tar_builder.into_inner().unwrap();
        let bundle_file_path = bundle_dir.join(format!("{}.grom",persona_name));
        fs::copy(&output_path,&bundle_file_path).unwrap();
        if let Ok(relative_path) = output_path.strip_prefix(&manifest_dir) {
          println!("cargo:warning=Auto-bundled persona: {}",relative_path.display());
        } else {
          println!("cargo:warning=Auto-bundled persona: {}",output_path.display());
        }
        personas.push(persona_name);
      }
    }
  }
  writeln!(codegen_file, "#[cfg(all(feature = \"gromrik\", feature = \"lyranis\"))]").unwrap();
  writeln!(codegen_file, "pub(crate) const BUNDLE_LIST: &[&str] = &[").unwrap();
  for persona in &personas {
    writeln!(codegen_file, "  \"{}\",", persona).unwrap();
  }
  writeln!(codegen_file, "];\n").unwrap();
  writeln!(codegen_file, "#[cfg(all(feature = \"gromrik\", feature = \"lyranis\"))]").unwrap();
  writeln!(codegen_file, "pub(crate) const BUNDLED_PERSONAS: &[&[u8]] = &[").unwrap();
  for persona in &personas {
    writeln!(codegen_file,"  include_bytes!(\"../resources/{}/{}.grom\"),",persona,persona).unwrap();
  }
  writeln!(codegen_file, "];").unwrap();
}
