[package]
name = "gromrik"
license = "MIT"
authors = ["Bethany Davis <ellis@despoena.com>"]
description = "A Displeased Dwarf Chat Bot"
repository = "https://github.com/countessellis/gromrik"
homepage = "https://github.com/countessellis/gromrik"
readme = "README.md"
version = "0.1.0"
edition = "2024"

[dependencies]
ansi_term = "0.12"
chrono = "0.4"
crossbeam-channel = "0.5"
dirs = "6.0"
eframe = "0.35"
egui_extras = { version = "0.35", features = ["all_loaders"] }
env_logger = "0.11"
image = { version = "0.25", features = ["png"] }
log = "0.4"
mimalloc = { version = "0.1", default-features = false }
ratatui = "0.30"
regex = "1.12"
reqwest = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ureq = { version = "3.3", features = ["json"] }
url = "2.5"

[build-dependencies]
chrono = "0.4"

[profile.dev]
opt-level = 1
debug = true

[profile.release]
opt-level = 3
strip = true
lto = true
codegen-units = 1
panic = "abort"
debug-assertions = false
overflow-checks = false
package."*".opt-level = "s"

