// =========================================================================
// AUTOMATICALLY GENERATED FILE - DO NOT EDIT MANUALLY
// =========================================================================
// This file is generated by the build.rs script during compilation.
// It scans the 'resources/' directory and embeds all valid '.grom' bundles
// straight into the application binary as static byte slices.
// =========================================================================

#[cfg(all(feature = "gromrik", feature = "lyranis"))]
pub(crate) const BUNDLE_LIST: &[&str] = &[
  "bramlink",
  "velissa",
  "lyranis",
  "gromrik",
  "zahirik",
];

#[cfg(all(feature = "gromrik", feature = "lyranis"))]
pub(crate) const BUNDLED_PERSONAS: &[&[u8]] = &[
  include_bytes!("../resources/bramlink/bramlink.grom"),
  include_bytes!("../resources/velissa/velissa.grom"),
  include_bytes!("../resources/lyranis/lyranis.grom"),
  include_bytes!("../resources/gromrik/gromrik.grom"),
  include_bytes!("../resources/zahirik/zahirik.grom"),
];
